Bot:
  # The bot token.
  token: ""

  # The default bot prefix.
  prefix: "~"

  # List of bot developer names.
  devs:
  - "CENSURADO"

  # List of bot helper names.
  helpers:
  - "CENSURADO"

  # List of bot owner's discord ids, as integers.
  owners:
  -

  colour: 0xff0000  # A hexadecimal colour used for embeds.

  # Whether the bot is a private instance or not.
  private: false

  # True to enable console logging.
  console logging: true

  # True to enable safe shutdown.
  safe shutdown: false

  # True to automaticlly update the bot.
  auto update: true

Bot extra:
  # A valid danbooru tag to represent bot's character.
  waifu name: "CENSURADO"

  # Bot's support guild.
  support: "CENSURADO"

  # Bot twitter page.
  twitter: "CENSURADO"

  # Bot website.
  website: "CENSURADO"

  # Bot invite link.
  invite: "CENSURADO"

  # Error log channel id, must be an integer.
  error log: 0

Bot lists:
  abal discord list: ""
  discord bots dot org: ""
  bots_discord_pw: ""
  carbonitex:
    compliant: false
    key: ""

API keys:
  # DiscordTel service. Public CENSURADO only needs this so no need to enable it.
  discordtel: false
  # Danbooru username and api key. More info here: https://danbooru.donmai.us/wiki_pages/43568
  danbooru:
    username: ""
    key: ""

  # CENSURADOapi key. More info here: discord.gg/y5MPvUC
  CENSURADOapi: ""

  # Edamam app id and key. More info here: https://www.edamam.com/
  edamam:
    app id: ""
    key: ""

  # OpenWeatherMap api key. More info here: https://openweathermap.org/api
  openweathermap: ""

# Config for the Postgres database.
Postgres:
  # Database host address or a path to the directory containing database server UNIX socket.
  host: ""

  # Connection port number.
  port: ""

  # The name of the database role used for authentication.
  user: ""

  # The name of the database.
  database: ""

  # Password used for authentication.
  password: ""

  # Schema name for the database.
  schema: ""
